import "./globals.css";
import "mapbox-gl/dist/mapbox-gl.css";
import Navbar from "../../components/layout/Header";
import Footer from "../../components/layout/Footer";

export const metadata = {
  title: "Gestor de proyectos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="mainContent">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
